[package]
name = "unitb"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "2c84af163dbc83c6eb6a94a03d5c25f25b6b8623"}
lean-lib = {git = "https://github.com/unitb/lean-lib", rev = "688388626295a2738c8985afaba4dbef0959e351"}
temporal-logic = {git = "https://github.com/unitb/temporal-logic", rev = "8149cbc7a3794a5c1a646ffdda5a78c006da6549"}
