[package]
name = "unitb"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "0ac694c04ab68428e65671f20cf0696280689b56"}
lean-lib = {git = "https://github.com/unitb/lean-lib", rev = "60143a36526235e4bbc21dbcddb39be602867e6e"}
temporal-logic = {git = "https://github.com/unitb/temporal-logic", rev = "b3a852012f9b156e3bf114ab4b630fa8e1b667df"}
