[package]
name = "unitb"
version = "0.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "7c72de2be1a07dcd00d343d720162c105d48107b"}
lean-lib = {git = "https://github.com/unitb/lean-lib", rev = "f1494cd2b2568c8662a10ebc03db11ecc1be5826"}
